version: '1.0'

services:
  backend:
    build: ./show-me-the-money-be
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    depends_on:
      - xero-api
    networks:
      - app-network

  frontend:
    build: ./show-me-the-money-fe
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:3002/api/balance-sheet
    depends_on:
      - backend

  xero-api:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge